stages:
  download:
    cmd: python scripts/data_load.py
    deps:
    - scripts/data_load.py
    outs:
    - data/california_housing.csv
  validate:
    cmd: python scripts/data_validate.py
    deps:
    - data/california_housing.csv
    - scripts/data_validate.py
    outs:
    - metrics/data_correlation_matrix.png
    - metrics/data_histogram.png
    metrics:
    - metrics/data_report.txt
  prepare:
    cmd: python scripts/prepare.py
    deps:
    - data/california_housing.csv
    - scripts/prepare.py
    outs:
    - data/california_housing_prepared.csv
  train:
    cmd: python scripts/train.py
    deps:
    - data/california_housing_prepared.csv
    - scripts/train.py
    outs:
    - models/rf_model.joblib
    params:
    - train.n_estimators
    - train.random_state
    - train.test_size
  evaluate:
    cmd: python scripts/evaluate.py
    deps:
    - models/rf_model.joblib
    - scripts/evaluate.py
  metrics:
    cmd: python scripts/metrics.py
    deps:
    - data/california_housing_prepared.csv
    - models/rf_model.joblib
    - scripts/metrics.py
    outs:
    - metrics/mse_plot.png
    metrics:
    - metrics/mse_values.csv
